import 'dart:io';

abstract class FileGenerator {
  static const _dontChangeHeader = '''
// Generated by serverpod_admin
// This file is generated, DO NOT CHANGE BY HAND
''';

  String get path;

  Future<String> fileContent();

  Future<void> createFile() async {
    print('Generating and creating file: $path');
    final content = await fileContent();
    final file = File(path);
    if (!file.existsSync()) {
      await file.create(recursive: true);
    }

    await file.writeAsString('''
$_dontChangeHeader
$content
''');
  }
}
