name: serverpod_admin
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  # serverpod admin
  yaml: ^3.1.3
  recase: ^4.1.0  
  uuid: ^4.5.1
  # serverpod admin end
  collection: ^1.19.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
